-- Compatibility migration for the existing push_subscriptions table.
create extension if not exists pgcrypto;

alter table public.push_subscriptions add column if not exists user_name text;
alter table public.push_subscriptions add column if not exists user_email text;
alter table public.push_subscriptions add column if not exists status text not null default 'active';
alter table public.push_subscriptions add column if not exists updated_at timestamptz not null default now();

-- Run this constraint only once if it does not already exist.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'push_subscriptions_status_check') then
    alter table public.push_subscriptions add constraint push_subscriptions_status_check check (status in ('active', 'unsubscribed'));
  end if;
end $$;

create table if not exists public.subscription_events (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  action text not null check (action in ('subscribe', 'unsubscribe')),
  created_at timestamptz not null default now()
);

create index if not exists push_subscriptions_status_idx on public.push_subscriptions(status);
create index if not exists push_subscriptions_created_at_idx on public.push_subscriptions(created_at desc);
create index if not exists subscription_events_created_at_idx on public.subscription_events(created_at desc);

alter table public.push_subscriptions enable row level security;
alter table public.subscription_events enable row level security;

drop policy if exists "public can insert push subscriptions" on public.push_subscriptions;
create policy "public can insert push subscriptions"
  on public.push_subscriptions for insert to anon, authenticated with check (true);

drop policy if exists "public can insert subscription events" on public.subscription_events;
create policy "public can insert subscription events"
  on public.subscription_events for insert to anon, authenticated with check (true);

-- No public SELECT, UPDATE, or DELETE policies are intentionally created.
